// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqqxqjyIcbsIof3S-GDCP6TpwLJZOq2qs',
    appId: '1:437060335509:web:e68f1b0da12f7d3fff289c',
    messagingSenderId: '437060335509',
    projectId: 'fir-training-b5da5',
    authDomain: 'fir-training-b5da5.firebaseapp.com',
    databaseURL: 'https://fir-training-b5da5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-training-b5da5.appspot.com',
    measurementId: 'G-N3KGWVJS0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsboSdTwjlSq-a5YG_itjQKxf6WCLsNoo',
    appId: '1:437060335509:android:48a020d312479dcfff289c',
    messagingSenderId: '437060335509',
    projectId: 'fir-training-b5da5',
    databaseURL: 'https://fir-training-b5da5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-training-b5da5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR_8coSbWRglkUKnZobn58PNHK9YtSFXM',
    appId: '1:437060335509:ios:3998cef1c90a5912ff289c',
    messagingSenderId: '437060335509',
    projectId: 'fir-training-b5da5',
    databaseURL: 'https://fir-training-b5da5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-training-b5da5.appspot.com',
    iosClientId: '437060335509-8mp6sr76ukd54on6cmp4f2o6ldmvbgef.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTrainingAppRevamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR_8coSbWRglkUKnZobn58PNHK9YtSFXM',
    appId: '1:437060335509:ios:3998cef1c90a5912ff289c',
    messagingSenderId: '437060335509',
    projectId: 'fir-training-b5da5',
    databaseURL: 'https://fir-training-b5da5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-training-b5da5.appspot.com',
    iosClientId: '437060335509-8mp6sr76ukd54on6cmp4f2o6ldmvbgef.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTrainingAppRevamp',
  );
}
